### ISSUE TITLE
No suitable image found - mach-o, but wrong architecture

### ISSUE THREAD

**Issue by Calderis** [node-usb/node-usb-example-electron#1] opened 2022-01-14 10:48 UTC
Hi, thanks for your library, it does help a lot.
When I try to start your node-usb-example-electron on a Mac M1 I have the following error : 
```
App threw an error during load
Error: dlopen(/Users/mysessions/Projects/node-usb-example-electron/node_modules/usb/prebuilds/darwin-x64+arm64/node.napi.node, 1): no suitable image found.  Did find:
	/Users/mysessions/Projects/node-usb-example-electron/node_modules/usb/prebuilds/darwin-x64+arm64/node.napi.node: mach-o, but wrong architecture
	/Users/mysessions/Projects/node-usb-example-electron/node_modules/usb/prebuilds/darwin-x64+arm64/node.napi.node: mach-o, but wrong architecture
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at load (/Users/mysessions/Projects/node-usb-example-electron/node_modules/node-gyp-build/index.js:21:10)
    at Object.<anonymous> (/Users/mysessions/Projects/node-usb-example-electron/node_modules/usb/dist/usb/bindings.js:8:36)
```
All what I did was simply cloning, installing the repo and starting it.

Node: 14.18.2
Electron : 16.0.4
usb: 2.0.3
Mac M1 on terminal used with Rosetta

I recently updated Electron from **11** to **16** and did not encounter this error previously (still on Mac M1 with Rosetta and same Node version). Did you have any idea ?

**Comment by Calderis** [comment] 2022-01-14 12:07
it does run with :
- electron 11.0.0 and usb 1.6.3
- electron 12.2.3 and usb 2.0.3
- electron 13.6.6 and usb 2.0.3
- electron 14.2.3 and usb 2.0.3

Does not work starting Electron 15.0.0 and usb 2.0.3

**Comment by dohooo** [comment] 2022-01-23 11:27
Node: 16.13.1
Electron : 16.0.5
usb: 2.0.3
Mac M1 on terminal used with Rosetta

I've made the same mistake as you. Is there any good way？ @Calderis

**Comment by dohooo** [comment] 2022-01-27 07:51
@thegecko help...

**Comment by dohooo** [comment] 2022-01-27 07:52
Is this an M1 specific problem？

**Comment by thegecko** [comment] 2022-01-29 23:53
This was caused by the `node-usb` library not having a universal binary set up properly.

Fixed in https://github.com/node-usb/node-usb/pull/473 and `usb@2.1.0`

This example repo now works as expected on M1

**Closed as completed by thegecko** 2022-01-29 23:53 UTC
